In [3]:
import pandas as pd

In [4]:
df = pd.read_excel('tester.xlsx', sheet_name='Sheet1')

In [5]:
print(df)

   Unnamed: 0      Unnamed: 1 Unnamed: 2       Unnamed: 3 Unnamed: 4  \
0         NaN  IB Gantry Edge        NaN  IB Centre Point        NaN
1         NaN            Lat        Long             Lat        Long
2      TP1 IB        -37.8005     145.19         -37.8004     145.19
3      TP1 OB             NaN        NaN              NaN        NaN
4         TP2         -37.824    145.217          -37.824    145.217
5         TP3        -37.8394    145.217         -37.8394    145.218
6         TP4        -37.8546    145.214         -37.8547    145.214
7         TP5         -37.869    145.211          -37.869    145.211
8         TP6        -37.8866    145.215         -37.8866    145.215
9         TP7        -37.9121    145.216         -37.9121    145.216
10        TP8        -37.9314     145.21         -37.9315     145.21
11        TP9        -37.9614    145.198         -37.9614    145.199
12       TP10        -37.9856    145.193         -37.9856    145.193
13       TP11        -38.0056     145.19         -38.0057     145.19
14       TP12        -38.0543    145.185         -38.0544    145.185
15       TP13        -38.0868    145.167         -38.0869    145.167

             Unnamed: 5 Unnamed: 6       Unnamed: 7 Unnamed: 8  \
0   Median Centre Point        NaN  OB Centre Point        NaN
1                  Lat        Long             Lat        Long
2              -37.8003     145.19              NaN        NaN
3              -37.8003     145.19         -37.8001     145.19
4               -37.824    145.217          -37.824    145.218
5              -37.8394    145.218         -37.8394    145.218
6              -37.8547    145.214         -37.8547    145.214
7               -37.869    145.211          -37.869    145.212
8              -37.8866    145.215         -37.8866    145.215
9              -37.9121    145.216         -37.9121    145.216
10             -37.9315     145.21         -37.9316     145.21
11             -37.9615    145.199         -37.9616    145.199
12             -37.9856    145.193         -37.9856    145.193
13             -38.0057     145.19         -38.0057     145.19
14             -38.0544    145.185         -38.0544    145.185
15              -38.087    145.168          -38.087    145.168

        Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13  \
0   OB Gantry edge         NaN  IB Heading  OB heading    IB Width
1             Lat         Long         Deg         Deg           m
2              NaN         NaN       259.2         NaN       13.78
3         -37.8002      145.19         NaN        77.7         NaN
4          -37.824     145.218       359.1       179.1       13.78
5         -37.8394     145.218       359.4       179.2       10.37
6         -37.8548     145.214        17.8       198.2       10.39
7          -37.869     145.212       357.7       177.7       10.49
8         -37.8866     145.215         1.2       180.7       10.65
9         -37.9121     145.216           1       180.9       14.18
10        -37.9316      145.21        24.8       204.2       13.95
11        -37.9617     145.199        33.1       214.3        14.1
12        -37.9856     145.193         2.4       183.4       10.35
13        -38.0058      145.19        14.3       194.5       14.08
14        -38.0544     145.185           9       188.8       10.44
15        -38.0872     145.168        68.1       247.5        7.18

   Unnamed: 14                                        Unnamed: 15
0     OB Width                                                NaN
1            m                                            Comment
2          NaN  IB gantry is not central on carriageway. Centr...
3         10.4                                                NaN
4         13.9  IB 4 lanes including a turning lane. Picked be...
5        10.37                                                NaN
6        10.43                                                NaN
7        10.37                                                NaN
8        10.54                                                NaN
9        10.24  TP7, 4 lanes inbound, 3 outbound with the serv...
10       13.93                                                NaN
11       13.86                                                NaN
12       10.47                                                NaN
13       13.91                                                NaN
14       10.45                                                NaN
15        6.98                                                NaN

In [9]:
print(df.values.tolist())

[[nan, 'IB Gantry Edge', nan, 'IB Centre Point', nan, 'Median Centre Point', nan, 'OB Centre Point', nan, 'OB Gantry edge', nan, 'IB Heading', 'OB heading', 'IB Width', 'OB Width', nan], [nan, 'Lat ', 'Long', 'Lat ', 'Long', 'Lat ', 'Long', 'Lat ', 'Long', 'Lat ', 'Long', 'Deg', 'Deg', 'm', 'm', 'Comment'], ['TP1 IB', -37.80049, 145.190474, -37.800353, 145.190437, -37.800272, 145.190424, nan, nan, nan, nan, 259.2, nan, 13.78, nan, 'IB gantry is not central on carriageway. Centre point as noted is between lanes 2 and 3 (centre of roadway)'], ['TP1 OB', nan, nan, nan, nan, -37.800328, 145.19008, -37.800089, 145.19001, -37.800222, 145.190047, nan, 77.7, nan, 10.4, nan], ['TP2', -37.824009, 145.21718, -37.824014, 145.217327, -37.82401, 145.217487, -37.824009, 145.217646, -37.824001, 145.217835, 359.1, 179.1, 13.78, 13.9, 'IB 4 lanes including a turning lane. Picked between lanes 2 and 3. IB width is three running plus 1 turn'], ['TP3', -37.839377, 145.217418, -37.839373, 145.217588, -37.839372, 145.217727, -37.839369, 145.217863, -37.839374, 145.218034, 359.4, 179.2, 10.37, 10.37, nan], ['TP4', -37.85461, 145.213827, -37.854652, 145.21399, -37.854684, 145.214121, -37.85472, 145.214253, -37.854763, 145.214413, 17.8, 198.2, 10.39, 10.43, nan], ['TP5', -37.86902, 145.211085, -37.869017, 145.211254, -37.869013, 145.21139, -37.869009, 145.21153, -37.869002, 145.211699, 357.7, 177.7, 10.49, 10.37, nan], ['TP6', -37.886581, 145.214588, -37.886563, 145.214759, -37.886565, 145.214899, -37.886563, 145.215037, -37.886568, 145.215206, 1.2, 180.7, 10.65, 10.54, nan], ['TP7', -37.912082, 145.215815, -37.912087, 145.215963, -37.912091, 145.216122, -37.912092, 145.216263, -37.912094, 145.216431, 1, 180.9, 14.18, 10.24, 'TP7, 4 lanes inbound, 3 outbound with the service centre turning lane diverging in the toll point.'], ['TP8', -37.931415, 145.209694, -37.931464, 145.209827, -37.931512, 145.209972, -37.931566, 145.21012, -37.931614, 145.210252, 24.8, 204.2, 13.95, 13.93, nan], ['TP9', -37.961374, 145.198408, -37.961443, 145.19854, -37.961513, 145.198671, -37.961586, 145.198803, -37.961665, 145.19895, 33.1, 214.3, 14.1, 13.86, nan], ['TP10', -37.985594, 145.192803, -37.985605, 145.192972, -37.98561, 145.193125, -37.985615, 145.193283, -37.985623, 145.193451, 2.4, 183.4, 10.35, 10.47, nan], ['TP11', -38.005619, 145.189751, -38.005656, 145.189933, -38.005689, 145.190104, -38.005723, 145.190277, -38.005762, 145.190462, 14.3, 194.5, 14.08, 13.91, nan], ['TP12', -38.054349, 145.184508, -38.05437, 145.184677, -38.054387, 145.184829, -38.054407, 145.184987, -38.054428, 145.185154, 9, 188.8, 10.44, 10.45, nan], ['TP13', -38.086759, 145.167436, -38.086869, 145.167488, -38.086955, 145.167534, -38.087045, 145.167582, -38.087151, 145.167639, 68.1, 247.5, 7.18, 6.98, nan]]

In [10]:
x = df.values.tolist()

In [11]:
print(x)

[[nan, 'IB Gantry Edge', nan, 'IB Centre Point', nan, 'Median Centre Point', nan, 'OB Centre Point', nan, 'OB Gantry edge', nan, 'IB Heading', 'OB heading', 'IB Width', 'OB Width', nan], [nan, 'Lat ', 'Long', 'Lat ', 'Long', 'Lat ', 'Long', 'Lat ', 'Long', 'Lat ', 'Long', 'Deg', 'Deg', 'm', 'm', 'Comment'], ['TP1 IB', -37.80049, 145.190474, -37.800353, 145.190437, -37.800272, 145.190424, nan, nan, nan, nan, 259.2, nan, 13.78, nan, 'IB gantry is not central on carriageway. Centre point as noted is between lanes 2 and 3 (centre of roadway)'], ['TP1 OB', nan, nan, nan, nan, -37.800328, 145.19008, -37.800089, 145.19001, -37.800222, 145.190047, nan, 77.7, nan, 10.4, nan], ['TP2', -37.824009, 145.21718, -37.824014, 145.217327, -37.82401, 145.217487, -37.824009, 145.217646, -37.824001, 145.217835, 359.1, 179.1, 13.78, 13.9, 'IB 4 lanes including a turning lane. Picked between lanes 2 and 3. IB width is three running plus 1 turn'], ['TP3', -37.839377, 145.217418, -37.839373, 145.217588, -37.839372, 145.217727, -37.839369, 145.217863, -37.839374, 145.218034, 359.4, 179.2, 10.37, 10.37, nan], ['TP4', -37.85461, 145.213827, -37.854652, 145.21399, -37.854684, 145.214121, -37.85472, 145.214253, -37.854763, 145.214413, 17.8, 198.2, 10.39, 10.43, nan], ['TP5', -37.86902, 145.211085, -37.869017, 145.211254, -37.869013, 145.21139, -37.869009, 145.21153, -37.869002, 145.211699, 357.7, 177.7, 10.49, 10.37, nan], ['TP6', -37.886581, 145.214588, -37.886563, 145.214759, -37.886565, 145.214899, -37.886563, 145.215037, -37.886568, 145.215206, 1.2, 180.7, 10.65, 10.54, nan], ['TP7', -37.912082, 145.215815, -37.912087, 145.215963, -37.912091, 145.216122, -37.912092, 145.216263, -37.912094, 145.216431, 1, 180.9, 14.18, 10.24, 'TP7, 4 lanes inbound, 3 outbound with the service centre turning lane diverging in the toll point.'], ['TP8', -37.931415, 145.209694, -37.931464, 145.209827, -37.931512, 145.209972, -37.931566, 145.21012, -37.931614, 145.210252, 24.8, 204.2, 13.95, 13.93, nan], ['TP9', -37.961374, 145.198408, -37.961443, 145.19854, -37.961513, 145.198671, -37.961586, 145.198803, -37.961665, 145.19895, 33.1, 214.3, 14.1, 13.86, nan], ['TP10', -37.985594, 145.192803, -37.985605, 145.192972, -37.98561, 145.193125, -37.985615, 145.193283, -37.985623, 145.193451, 2.4, 183.4, 10.35, 10.47, nan], ['TP11', -38.005619, 145.189751, -38.005656, 145.189933, -38.005689, 145.190104, -38.005723, 145.190277, -38.005762, 145.190462, 14.3, 194.5, 14.08, 13.91, nan], ['TP12', -38.054349, 145.184508, -38.05437, 145.184677, -38.054387, 145.184829, -38.054407, 145.184987, -38.054428, 145.185154, 9, 188.8, 10.44, 10.45, nan], ['TP13', -38.086759, 145.167436, -38.086869, 145.167488, -38.086955, 145.167534, -38.087045, 145.167582, -38.087151, 145.167639, 68.1, 247.5, 7.18, 6.98, nan]]

In [12]:
for i in x:
    print(i)

[nan, 'IB Gantry Edge', nan, 'IB Centre Point', nan, 'Median Centre Point', nan, 'OB Centre Point', nan, 'OB Gantry edge', nan, 'IB Heading', 'OB heading', 'IB Width', 'OB Width', nan]
[nan, 'Lat ', 'Long', 'Lat ', 'Long', 'Lat ', 'Long', 'Lat ', 'Long', 'Lat ', 'Long', 'Deg', 'Deg', 'm', 'm', 'Comment']
['TP1 IB', -37.80049, 145.190474, -37.800353, 145.190437, -37.800272, 145.190424, nan, nan, nan, nan, 259.2, nan, 13.78, nan, 'IB gantry is not central on carriageway. Centre point as noted is between lanes 2 and 3 (centre of roadway)']
['TP1 OB', nan, nan, nan, nan, -37.800328, 145.19008, -37.800089, 145.19001, -37.800222, 145.190047, nan, 77.7, nan, 10.4, nan]
['TP2', -37.824009, 145.21718, -37.824014, 145.217327, -37.82401, 145.217487, -37.824009, 145.217646, -37.824001, 145.217835, 359.1, 179.1, 13.78, 13.9, 'IB 4 lanes including a turning lane. Picked between lanes 2 and 3. IB width is three running plus 1 turn']
['TP3', -37.839377, 145.217418, -37.839373, 145.217588, -37.839372, 145.217727, -37.839369, 145.217863, -37.839374, 145.218034, 359.4, 179.2, 10.37, 10.37, nan]
['TP4', -37.85461, 145.213827, -37.854652, 145.21399, -37.854684, 145.214121, -37.85472, 145.214253, -37.854763, 145.214413, 17.8, 198.2, 10.39, 10.43, nan]
['TP5', -37.86902, 145.211085, -37.869017, 145.211254, -37.869013, 145.21139, -37.869009, 145.21153, -37.869002, 145.211699, 357.7, 177.7, 10.49, 10.37, nan]
['TP6', -37.886581, 145.214588, -37.886563, 145.214759, -37.886565, 145.214899, -37.886563, 145.215037, -37.886568, 145.215206, 1.2, 180.7, 10.65, 10.54, nan]
['TP7', -37.912082, 145.215815, -37.912087, 145.215963, -37.912091, 145.216122, -37.912092, 145.216263, -37.912094, 145.216431, 1, 180.9, 14.18, 10.24, 'TP7, 4 lanes inbound, 3 outbound with the service centre turning lane diverging in the toll point.']
['TP8', -37.931415, 145.209694, -37.931464, 145.209827, -37.931512, 145.209972, -37.931566, 145.21012, -37.931614, 145.210252, 24.8, 204.2, 13.95, 13.93, nan]
['TP9', -37.961374, 145.198408, -37.961443, 145.19854, -37.961513, 145.198671, -37.961586, 145.198803, -37.961665, 145.19895, 33.1, 214.3, 14.1, 13.86, nan]
['TP10', -37.985594, 145.192803, -37.985605, 145.192972, -37.98561, 145.193125, -37.985615, 145.193283, -37.985623, 145.193451, 2.4, 183.4, 10.35, 10.47, nan]
['TP11', -38.005619, 145.189751, -38.005656, 145.189933, -38.005689, 145.190104, -38.005723, 145.190277, -38.005762, 145.190462, 14.3, 194.5, 14.08, 13.91, nan]
['TP12', -38.054349, 145.184508, -38.05437, 145.184677, -38.054387, 145.184829, -38.054407, 145.184987, -38.054428, 145.185154, 9, 188.8, 10.44, 10.45, nan]
['TP13', -38.086759, 145.167436, -38.086869, 145.167488, -38.086955, 145.167534, -38.087045, 145.167582, -38.087151, 145.167639, 68.1, 247.5, 7.18, 6.98, nan]

In [23]:
for i in x:
    if isinstance(i[0], str):
        print(i[0])

TP1 IB
TP1 OB
TP2
TP3
TP4
TP5
TP6
TP7
TP8
TP9
TP10
TP11
TP12
TP13

In [32]:
import json

In [37]:
arr = []

for i in x:
    if isinstance(i[0], str):
        if i[0].find("B") != -1:
            
            if i[0].find("IB"):
                item = {}
                item["id"] = i[0]
                item["lat"] = i[3]
                item["lng"] = i[4]
                arr.append(item)
            else:
                item = {}
                item["id"] = i[0]
                item["lat"] = i[3]
                item["lng"] = i[4]
                arr.append(item)
        else:
            print(i[0])
            
print(arr)

with open("data.json", "w") as f:
    json.dump(arr, f, indent=4)

TP2
TP3
TP4
TP5
TP6
TP7
TP8
TP9
TP10
TP11
TP12
TP13
[{'name': 'TP1 IB'}, {'name': 'TP1 OB'}]